dist: xenial

language: python

python:
  - 3.6
  - 3.7

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 .
  - poetry run mypy dotenv_linter
  - poetry run pytest
  - poetry run doc8 -q docs
  - poetry run safety check --bare --full-report
  - poetry check
  - poetry run pip check

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
